---
# Task for configure reverse proxy

- name: Nginx config | Copy nginx.conf file
  become: True
  ansible.builtin.template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

#- name: Nginx config | Copy hosts file
#  become: True
#  ansible.builtin.template:
#    src: templates/hosts.j2
#    dest: /etc/hosts

- name: Nginx config | Copy config files
  become: True
  ansible.builtin.template:
    src: templates/{{ item }}.conf.j2
    dest: /etc/nginx/sites-available/{{ item }}.conf
  with_items: "{{ domain_zones }}"

- name: Nginx config | Enable sites
  become: True
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{ item }}.conf
    dest: /etc/nginx/sites-enabled/{{ item }}
    state: link
  with_items: "{{ domain_zones }}"
  
- name: Nginx config | Disable default
  become: True
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Nginx reload