---
# handlers file for reverse-proxy-nginx
- name: Nginx start
  become: true
  ansible.builtin.systemd:
    state: started
    name: nginx
    
- name: Nginx reload
  become: true
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: nginx